import PinUtilities

public struct CodeGenerator {
    // MARK: Properties

    private let components: [ComponentInfo]
    private let imports: [String]
    /// Lookup from class name to component info for subcomponent access level resolution.
    private let componentsByName: [String: ComponentInfo]

    // MARK: Lifecycle

    public init(components: [ComponentInfo], imports: [String]) {
        self.components = components
        self.imports = imports
        var map: [String: ComponentInfo] = [:]
        for component in components {
            map[component.className] = component
        }
        self.componentsByName = map
    }

    // MARK: Functions

    /// Detects circular subcomponent relationships such as A → B → A.
    ///
    /// Returns error messages for each cycle found, or an empty array.
    public func detectCycles() -> [String] {
        // Build adjacency list: className → [child classNames]
        var adjacency: [String: [String]] = [:]
        for component in components {
            adjacency[component.className] = component.subcomponents.map(\.typeName)
        }

        var visited: Set<String> = []
        var inStack: Set<String> = []
        var errors: [String] = []

        func dfs(_ node: String, path: [String]) {
            if inStack.contains(node) {
                guard let cycleStart = path.firstIndex(of: node) else {
                    return
                }
                let cycle = path[cycleStart...] + [node]
                errors.append(
                    "Circular subcomponent dependency: \(cycle.joined(separator: " → "))"
                )
                return
            }
            guard !visited.contains(node) else {
                return
            }
            visited.insert(node)
            inStack.insert(node)
            for child in adjacency[node] ?? [] {
                dfs(child, path: path + [node])
            }
            inStack.remove(node)
        }

        for component in components {
            dfs(component.className, path: [])
        }

        return errors
    }

    public func generate() -> String {
        if components.isEmpty {
            return "// No @PinComponent classes found in this target.\n"
        }

        var lines: [String] = []

        lines.append("// Auto-generated by PinPlugin. Do not edit.")
        lines.append("")

        // Deduplicated imports
        let uniqueImports = Array(Set(imports)).sorted()
        for imp in uniqueImports {
            lines.append(imp)
        }
        if !uniqueImports.isEmpty {
            lines.append("")
        }

        for component in components {
            lines.append(contentsOf: generateComponent(component))
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    private func generateComponent(_ component: ComponentInfo) -> [String] {
        var lines: [String] = []
        let access = component.accessLevel.declarationPrefix
        let accessor = escapedIfKeyword(lowercasePrefix(component.className))

        // Split subcomponents into public and internal tiers based on their access level.
        // Subcomponents not found in this target (cross-target) are assumed public.
        let (publicSubs, internalSubs) = splitSubcomponents(component)

        let hasInternalTier = !component.internalProperties.isEmpty || !internalSubs.isEmpty

        // 1. Providing protocol (public tier — only public subcomponent inheritance)
        lines.append(
            contentsOf: generateProvidingProtocol(
                component,
                access: access,
                accessor: accessor,
                subcomponents: publicSubs
            )
        )
        lines.append("")

        // 1b. InternalProviding protocol (inherits public Providing + internal subcomponent protocols)
        if hasInternalTier {
            var internalInherited = ["\(component.className)Providing"]
            for sub in internalSubs {
                internalInherited.append("\(sub.typeName)Providing")
                internalInherited.append("\(sub.typeName)Dependency")
            }
            let inheritance = internalInherited.joined(separator: ", ")
            lines.append("@MainActor protocol \(component.className)InternalProviding: \(inheritance) {")
            lines.append("}")
            lines.append("")
        }

        // 2. Conformance extension (use InternalProviding when it exists)
        let conformanceProtocol =
            hasInternalTier
            ? "\(component.className)InternalProviding"
            : "\(component.className)Providing"
        lines.append("@MainActor extension \(component.className): \(conformanceProtocol) {}")
        lines.append("")

        // 3. Self-accessor extension
        lines.append("@MainActor extension \(component.className) {")
        lines.append("    \(access)var \(accessor): \(component.className) { self }")
        lines.append("}")

        // 4. Forwarding extensions (underscored only — clean names are provided
        //    by the Dependency default impl to avoid ambiguity across modules)
        if !component.properties.isEmpty {
            lines.append("")
            lines.append("@MainActor extension \(component.className)Providing {")
            for prop in component.properties {
                let underscored = escapedIfKeyword("_\(prop.name)")
                lines.append("    \(access)var \(underscored): \(prop.type) { \(accessor).\(prop.name) }")
            }
            lines.append("}")
        }

        // 4b. Internal forwarding extensions (on InternalProviding)
        if !component.internalProperties.isEmpty {
            lines.append("")
            lines.append("@MainActor extension \(component.className)InternalProviding {")
            for prop in component.internalProperties {
                let underscored = escapedIfKeyword("_\(prop.name)")
                lines.append("    var \(underscored): \(prop.type) { \(accessor).\(prop.name) }")
            }
            lines.append("}")
        }

        // 5. Dependency default implementations (bridge clean → underscored)
        if !component.dependencies.isEmpty {
            lines.append("")
            lines.append("@MainActor extension \(component.className)Dependency {")
            for dep in component.dependencies {
                let clean = escapedIfKeyword(dep.name)
                let underscored = escapedIfKeyword("_\(dep.name)")
                lines.append("    \(access)var \(clean): \(dep.type) { \(underscored) }")
            }
            lines.append("}")
        }

        // 6. Provider conformance extension
        if let provider = component.provider {
            lines.append("")
            lines.append("@MainActor extension \(provider): \(component.className)Dependency {}")
        }

        // 7. Subcomponent accessor extensions — split by tier
        if !publicSubs.isEmpty {
            lines.append("")
            lines.append("@MainActor extension \(component.className)Providing {")
            for sub in publicSubs {
                let subAccessor = escapedIfKeyword(lowercasePrefix(sub.typeName))
                let propRef = escapedIfKeyword(sub.propertyName)
                lines.append("    \(access)var \(subAccessor): \(sub.typeName) { \(accessor).\(propRef) }")
            }
            lines.append("}")
        }
        if !internalSubs.isEmpty {
            lines.append("")
            lines.append("@MainActor extension \(component.className)InternalProviding {")
            for sub in internalSubs {
                let subAccessor = escapedIfKeyword(lowercasePrefix(sub.typeName))
                let propRef = escapedIfKeyword(sub.propertyName)
                lines.append("    var \(subAccessor): \(sub.typeName) { \(accessor).\(propRef) }")
            }
            lines.append("}")
        }

        return lines
    }

    private func generateProvidingProtocol(
        _ component: ComponentInfo,
        access: String,
        accessor: String,
        subcomponents: [SubcomponentInfo]
    ) -> [String] {
        var inherited: [String] = []

        // Inherit from subcomponent Providings + Dependencies
        for sub in subcomponents {
            inherited.append("\(sub.typeName)Providing")
            inherited.append("\(sub.typeName)Dependency")
        }

        let inheritance = inherited.isEmpty ? "" : ": \(inherited.joined(separator: ", "))"

        return [
            "@MainActor \(access)protocol \(component.className)Providing\(inheritance) {",
            "    var \(accessor): \(component.className) { get }",
            "}",
        ]
    }

    /// Splits subcomponents into (public, internal) based on the child's access level.
    ///
    /// Subcomponents from other targets (not in the components list) are assumed public.
    private func splitSubcomponents(
        _ component: ComponentInfo
    ) -> (public: [SubcomponentInfo], internal: [SubcomponentInfo]) {
        // Only public/package components need the split — internal components
        // have everything at the same visibility level.
        guard component.accessLevel == .public || component.accessLevel == .package else {
            return (component.subcomponents, [])
        }

        var publicSubs: [SubcomponentInfo] = []
        var internalSubs: [SubcomponentInfo] = []

        for sub in component.subcomponents {
            if let child = componentsByName[sub.typeName] {
                // Same-target subcomponent: check its access level
                if child.accessLevel == .public || child.accessLevel == component.accessLevel {
                    publicSubs.append(sub)
                } else {
                    internalSubs.append(sub)
                }
            } else {
                // Cross-target subcomponent: must be public to be importable
                publicSubs.append(sub)
            }
        }

        return (publicSubs, internalSubs)
    }
}
