import SwiftSyntax
import SwiftSyntaxMacros

/// Scans a class for `@PinSubcomponent` properties and generates
/// `private lazy var _name: Type = Type(dependency: self)` backing stores.
///
/// Used by `@PinComponent` member expansions.
/// The backing store must be generated by a `@attached(member)` macro on the
/// class (not a peer macro on the property) because peer macros cannot add
/// stored properties to a class -- the compiler's IRGen doesn't account for
/// them in class layout.
func generateSubcomponentBackingStores(
    for classDecl: ClassDeclSyntax
) -> [DeclSyntax] {
    var results: [DeclSyntax] = []

    for member in classDecl.memberBlock.members {
        guard let varDecl = member.decl.as(VariableDeclSyntax.self) else {
            continue
        }

        let hasPinSubcomponent = varDecl.attributes.contains { attr in
            guard case .attribute(let attribute) = attr else {
                return false
            }
            return attribute.attributeName.trimmedDescription == "PinSubcomponent"
        }
        guard hasPinSubcomponent else {
            continue
        }

        guard let parsed = PinSubcomponentMacro.parseSubcomponent(from: varDecl) else {
            continue
        }

        let name = parsed.propertyName
        let type = parsed.typeName
        results.append(
            "private lazy var _\(raw: name): \(raw: type) = \(raw: type)(dependency: self)"
        )
    }

    return results
}
